from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.db.base import Base
from app.db import models  # noqa: F401

config = context.config


def _resolve_database_url() -> str:
    config_url = config.get_main_option('sqlalchemy.url')
    if config_url and config_url.strip():
        return config_url.strip()

    env_url = os.getenv('DATABASE_URL')
    if env_url and env_url.strip():
        return env_url.strip()

    from app.config import get_settings

    settings = get_settings()
    return settings.database_url


database_url = _resolve_database_url()
config.set_main_option('sqlalchemy.url', database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def process_revision_directives(context, revision, directives) -> None:
    """
    Не создавать пустые autogenerated-миграции.
    Полезно при частой работе file-by-file, чтобы не плодить пустые revision-файлы.
    """
    if not getattr(config.cmd_opts, 'autogenerate', False):
        return

    if not directives:
        return

    script = directives[0]
    if script.upgrade_ops.is_empty():
        directives[:] = []


def _configure_context(**kwargs) -> None:
    context.configure(
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        process_revision_directives=process_revision_directives,
        **kwargs,
    )


def run_migrations_offline() -> None:
    url = config.get_main_option('sqlalchemy.url')
    _configure_context(
        url=url,
        literal_binds=True,
        dialect_opts={'paramstyle': 'named'},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    _configure_context(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix='sqlalchemy.',
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    import asyncio

    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()